name=LCD_wo2004b-tfh
version=1.0.0
author=Alexander Antipov <alexander.antipov79@gmail.com>
maintainer=Alexander Antipov <alexander.antipov79@gmail.com>
sentence=Display Library for Winstar WO2004B-TFH
paragraph=Driver IST3602. Caution: WO2004B-TFH require 3.3V supply AND data lines!
category=Display
url=https://github.com/
architectures=esp8266, esp32, stm32
depends=ArduinoHttpClient